name = "JuliaPlot"
uuid = "7ee8c8ad-0ea8-44b4-812d-3927a13fcb47"
authors = ["David Gustavsson <david.e.gustavsson@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
